# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-07 15:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0002_auto_20180107_1511'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Employees'},
        ),
        migrations.AlterModelOptions(
            name='promissory',
            options={'verbose_name': 'Promissory Notes'},
        ),
    ]
