# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-28 21:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0003_auto_20180226_0721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promissory',
            old_name='emp_status',
            new_name='promissory_status',
        ),
    ]
