# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-07 15:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0003_auto_20180107_1556'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Employee'},
        ),
        migrations.AlterModelOptions(
            name='promissory',
            options={'verbose_name': 'Promissory Note'},
        ),
    ]
