# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-10 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeesAccounts',
            fields=[
                ('fa_ID', models.AutoField(primary_key=True, serialize=False)),
                ('fa_name', models.CharField(max_length=200)),
                ('amount', models.FloatField()),
            ],
            options={
                'verbose_name': 'List of Fees and Account',
            },
        ),
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('pdetails_ID', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Paid fees and account',
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('payment_ID', models.AutoField(primary_key=True, serialize=False)),
                ('payment_date', models.DateField()),
                ('total_amount', models.FloatField()),
                ('payment_type', models.CharField(choices=[('c', 'Cash'), ('q', 'Check'), ('o', 'Others')], default='c', max_length=1)),
                ('payment_note', models.CharField(max_length=200)),
                ('OR_number', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Payment Log',
            },
        ),
    ]
