# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-07 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeesAccounts',
            fields=[
                ('fa_ID', models.AutoField(primary_key=True, serialize=False)),
                ('fa_name', models.CharField(max_length=200)),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('pdetails_ID', models.AutoField(primary_key=True, serialize=False)),
                ('fa_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cashier.FeesAccounts')),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('payment_ID', models.AutoField(primary_key=True, serialize=False)),
                ('payment_date', models.DateField()),
                ('total_amount', models.FloatField()),
                ('payment_type', models.CharField(max_length=200)),
                ('payment_note', models.CharField(max_length=200)),
                ('OR_number', models.IntegerField()),
                ('enrollment_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.Enrollment')),
            ],
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='payment_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cashier.Payments'),
        ),
    ]
