# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-10 02:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cashier', '0001_initial'),
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='enrollment_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.Enrollment'),
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='fa_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cashier.FeesAccounts'),
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='payment_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cashier.Payments'),
        ),
    ]
