# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-07 15:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feesaccounts',
            options={'verbose_name': 'List of Fees and Accounts'},
        ),
        migrations.AlterModelOptions(
            name='paymentdetails',
            options={'verbose_name': 'Paid fees and accounts'},
        ),
        migrations.AlterModelOptions(
            name='payments',
            options={'verbose_name': 'Payment Logs'},
        ),
    ]
