# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-28 16:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0002_auto_20180209_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_ID', models.AutoField(primary_key=True, serialize=False)),
                ('enrollment_ID', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Account_Particular',
            fields=[
                ('account_particular_ID', models.AutoField(primary_key=True, serialize=False)),
                ('to_pay', models.FloatField()),
                ('account_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashier.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Daily_Cash',
            fields=[
                ('daily_cash_ID', models.AutoField(primary_key=True, serialize=False)),
                ('date_today', models.DateField(auto_now=True)),
                ('DCR_num', models.CharField(default=None, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Daily_Cash_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash', models.FloatField()),
                ('daily_cash_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashier.Daily_Cash')),
            ],
        ),
        migrations.CreateModel(
            name='Particular',
            fields=[
                ('particular_ID', models.AutoField(primary_key=True, serialize=False)),
                ('particular_name', models.CharField(max_length=100)),
                ('particular_details', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transact_ID', models.AutoField(primary_key=True, serialize=False)),
                ('date_time_created', models.DateTimeField(auto_now=True)),
                ('OR_num', models.BigIntegerField()),
                ('account_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashier.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction_Detail',
            fields=[
                ('transaction_detail_ID', models.AutoField(primary_key=True, serialize=False)),
                ('amount_paid', models.FloatField()),
                ('account_particular_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashier.Particular')),
                ('transact_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashier.Transaction')),
            ],
        ),
        migrations.RemoveField(
            model_name='paymentdetails',
            name='fa_ID',
        ),
        migrations.RemoveField(
            model_name='paymentdetails',
            name='payment_ID',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='enrollment_ID',
        ),
        migrations.DeleteModel(
            name='FeesAccounts',
        ),
        migrations.DeleteModel(
            name='PaymentDetails',
        ),
        migrations.DeleteModel(
            name='Payments',
        ),
        migrations.AddField(
            model_name='daily_cash_detail',
            name='transact_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashier.Transaction'),
        ),
        migrations.AddField(
            model_name='account_particular',
            name='particular_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashier.Particular'),
        ),
    ]
