# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-07 15:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0002_auto_20180107_1556'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feesaccounts',
            options={'verbose_name': 'List of Fees and Account'},
        ),
        migrations.AlterModelOptions(
            name='paymentdetails',
            options={'verbose_name': 'Paid fees and account'},
        ),
        migrations.AlterModelOptions(
            name='payments',
            options={'verbose_name': 'Payment Log'},
        ),
    ]
