# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-07 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enrollment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drop',
            fields=[
                ('drop_ID', models.AutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=200)),
                ('drop_date', models.DateField(auto_now=True)),
                ('reason', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=2)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('curriculum', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='enrollment.Curriculum')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('enrollment_ID', models.AutoField(primary_key=True, serialize=False)),
                ('student_type', models.IntegerField()),
                ('curriculum', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='enrollment.Curriculum')),
                ('scholarship_ID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='enrollment.Scholarship')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment_Details',
            fields=[
                ('enrollmentDetails_ID', models.AutoField(primary_key=True, serialize=False)),
                ('enrollment_ID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='registration.Enrollment')),
                ('offering_ID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='enrollment.Offering')),
            ],
        ),
        migrations.CreateModel(
            name='SHS_Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_subjectName', models.CharField(max_length=200)),
                ('s_desc', models.CharField(max_length=100)),
                ('s_status', models.CharField(choices=[('a', 'Active'), ('n', 'Inactive')], default='n', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_ID', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('a', 'Active'), ('n', 'Inactive')], default='n', max_length=1)),
                ('birthplace', models.CharField(max_length=200)),
                ('birthdate', models.DateField()),
                ('home_addr', models.CharField(max_length=200)),
                ('postal_addr', models.CharField(max_length=200)),
                ('m_firstname', models.CharField(max_length=200)),
                ('m_middlename', models.CharField(max_length=200)),
                ('m_lastname', models.CharField(max_length=200)),
                ('m_occcupation', models.CharField(max_length=200)),
                ('f_firstname', models.CharField(max_length=200)),
                ('f_middlename', models.CharField(max_length=200)),
                ('f_lastname', models.CharField(max_length=200)),
                ('f_occcupation', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['student_ID'],
            },
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student_ID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='registration.Student'),
        ),
    ]
