# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-03 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_remove_student_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('a', 'Active'), ('n', 'Inactive')], default='n', max_length=1),
        ),
    ]
