# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-07 15:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20180107_1556'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment_details',
            options={'verbose_name': 'Enrollment Detail'},
        ),
        migrations.AlterModelOptions(
            name='shs_subjects',
            options={'verbose_name': 'Senior High Subject'},
        ),
    ]
