# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-10 02:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrative', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('curriculum_ID', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Curriculum',
            },
        ),
        migrations.CreateModel(
            name='Offering',
            fields=[
                ('offering_ID', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Offered Subject',
            },
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scholarship_name', models.CharField(max_length=200)),
                ('scholarship_type', models.CharField(choices=[('e', 'ESC'), ('t', 'Others')], default='t', max_length=1)),
            ],
            options={
                'verbose_name': 'Scholarship',
            },
        ),
        migrations.CreateModel(
            name='School_Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_name', models.CharField(max_length=200)),
                ('date_start', models.DateField(auto_now=True)),
                ('date_end', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'School Year',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('section_ID', models.AutoField(primary_key=True, serialize=False)),
                ('section_name', models.CharField(max_length=50)),
                ('section_capacity', models.IntegerField()),
                ('room', models.CharField(max_length=50)),
                ('section_status', models.CharField(choices=[('a', 'Active'), ('i', 'Inactive')], default='i', max_length=1)),
            ],
            options={
                'verbose_name': 'Section',
            },
        ),
        migrations.CreateModel(
            name='Section_Enrollee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_status', models.CharField(choices=[('a', 'Active'), ('i', 'Inactive')], default='i', max_length=1)),
            ],
            options={
                'verbose_name': 'Enrollees in Sections',
            },
        ),
        migrations.CreateModel(
            name='Section_Offerings',
            fields=[
                ('sectionDetails_ID', models.AutoField(primary_key=True, serialize=False)),
                ('offering_ID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='enrollment.Offering')),
                ('section_ID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='enrollment.Section')),
            ],
            options={
                'verbose_name': 'Section Detail',
            },
        ),
        migrations.CreateModel(
            name='SHS_Offering',
            fields=[
                ('offering_ID', models.AutoField(primary_key=True, serialize=False)),
                ('school_year', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='enrollment.School_Year')),
            ],
            options={
                'verbose_name': 'Offered Subjects for SHS',
            },
        ),
        migrations.CreateModel(
            name='SHS_Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_subjectName', models.CharField(max_length=200)),
                ('s_subjectDesc', models.CharField(max_length=200)),
                ('s_desc', models.CharField(max_length=100)),
                ('s_status', models.CharField(choices=[('a', 'Active'), ('i', 'Inactive')], default='i', max_length=1)),
                ('s_curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enrollment.Curriculum')),
            ],
            options={
                'verbose_name': 'Senior High Subject',
            },
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('subject_ID', models.AutoField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=200)),
                ('subject_description', models.CharField(max_length=200)),
                ('subject_status', models.CharField(choices=[('a', 'Active'), ('o', 'On Leave'), ('i', 'Inactive')], default='i', max_length=1)),
                ('curriculum', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enrollment.Curriculum')),
            ],
            options={
                'verbose_name': 'Subject',
            },
        ),
        migrations.CreateModel(
            name='TeacherDetails',
            fields=[
                ('teacher_ID', models.AutoField(primary_key=True, serialize=False)),
                ('units', models.IntegerField()),
                ('employee_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrative.Employee')),
            ],
            options={
                'verbose_name': 'Details of Teacher',
            },
        ),
        migrations.CreateModel(
            name='YearLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_level', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='shs_offering',
            name='subject',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='enrollment.SHS_Subjects'),
        ),
        migrations.AddField(
            model_name='shs_offering',
            name='teacher',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='enrollment.TeacherDetails'),
        ),
    ]
