# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-07 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrative', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('curriculum_ID', models.AutoField(primary_key=True, serialize=False)),
                ('curriculum_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Offering',
            fields=[
                ('offering_ID', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Prerequisites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enrollment.Curriculum')),
            ],
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scholarship_name', models.CharField(max_length=200)),
                ('amount', models.IntegerField()),
                ('validity', models.BooleanField(default=False)),
                ('scholar_type', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='School_Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_name', models.CharField(max_length=200)),
                ('date_start', models.DateField(auto_now=True)),
                ('date_end', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('section_ID', models.AutoField(primary_key=True, serialize=False)),
                ('section_name', models.CharField(max_length=50)),
                ('section_status', models.CharField(choices=[('a', 'Active'), ('n', 'Inactive')], default='n', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='SHS_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
                ('type', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('subject_ID', models.AutoField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=50)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enrollment.Curriculum')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherDetails',
            fields=[
                ('teacher_ID', models.AutoField(primary_key=True, serialize=False)),
                ('units', models.IntegerField()),
                ('section_status', models.CharField(choices=[('a', 'Active'), ('n', 'Inactive')], default='n', max_length=1)),
                ('advised_section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enrollment.Sections')),
                ('employee_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrative.Employee')),
            ],
        ),
        migrations.AddField(
            model_name='scholarship',
            name='school_year',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='enrollment.School_Year'),
        ),
        migrations.AddField(
            model_name='offering',
            name='schoolYr_ID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='enrollment.School_Year'),
        ),
        migrations.AddField(
            model_name='offering',
            name='subject_ID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='enrollment.Subjects'),
        ),
        migrations.AddField(
            model_name='offering',
            name='teacher',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='administrative.Employee'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='school_year',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='enrollment.School_Year'),
        ),
    ]
