# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-07 15:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curriculum',
            options={'verbose_name': 'Curriculum'},
        ),
        migrations.AlterModelOptions(
            name='offering',
            options={'verbose_name': 'Offered Subjects'},
        ),
        migrations.AlterModelOptions(
            name='prerequisites',
            options={'verbose_name': 'Prerequisites'},
        ),
        migrations.AlterModelOptions(
            name='scholarship',
            options={'verbose_name': 'Scholarship'},
        ),
        migrations.AlterModelOptions(
            name='school_year',
            options={'verbose_name': 'School Year'},
        ),
        migrations.AlterModelOptions(
            name='sections',
            options={'verbose_name': 'Sections'},
        ),
        migrations.AlterModelOptions(
            name='shs_category',
            options={'verbose_name': 'Senior High Category'},
        ),
        migrations.AlterModelOptions(
            name='subjects',
            options={'verbose_name': 'Subjects'},
        ),
        migrations.AlterModelOptions(
            name='teacherdetails',
            options={'verbose_name': 'Details of Teachers'},
        ),
    ]
