# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-10 02:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enrollment', '0001_initial'),
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section_enrollee',
            name='enrollee',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='registration.Enrollment'),
        ),
        migrations.AddField(
            model_name='section_enrollee',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enrollment.Section'),
        ),
        migrations.AddField(
            model_name='section',
            name='adviser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enrollment.TeacherDetails'),
        ),
        migrations.AddField(
            model_name='section',
            name='curriculum',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enrollment.Curriculum'),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='school_year',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='enrollment.School_Year'),
        ),
        migrations.AddField(
            model_name='offering',
            name='school_year',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='enrollment.School_Year'),
        ),
        migrations.AddField(
            model_name='offering',
            name='subject',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='enrollment.Subjects'),
        ),
        migrations.AddField(
            model_name='offering',
            name='teacher',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='enrollment.TeacherDetails'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='school_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enrollment.School_Year'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='year_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enrollment.YearLevel'),
        ),
    ]
