# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-07 15:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0002_auto_20180107_1556'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offering',
            options={'verbose_name': 'Offered Subject'},
        ),
        migrations.AlterModelOptions(
            name='prerequisites',
            options={'verbose_name': 'Prerequisite'},
        ),
        migrations.AlterModelOptions(
            name='sections',
            options={'verbose_name': 'Section'},
        ),
        migrations.AlterModelOptions(
            name='subjects',
            options={'verbose_name': 'Subject'},
        ),
        migrations.AlterModelOptions(
            name='teacherdetails',
            options={'verbose_name': 'Details of Teacher'},
        ),
    ]
