# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-19 16:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0002_auto_20180209_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='offering',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='enrollment.Section'),
        ),
        migrations.AddField(
            model_name='offering',
            name='year_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='enrollment.YearLevel'),
        ),
    ]
