# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-07 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0003_auto_20180107_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='SHS_Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_subjectName', models.CharField(max_length=200)),
                ('s_desc', models.CharField(max_length=100)),
                ('s_status', models.CharField(choices=[('a', 'Active'), ('n', 'Inactive')], default='n', max_length=1)),
            ],
            options={
                'verbose_name': 'Senior High Subject',
            },
        ),
    ]
