# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-19 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0003_auto_20180219_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='offering',
            name='units',
            field=models.IntegerField(null=True),
        ),
    ]
