# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-07 16:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0004_shs_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offering',
            name='teacher',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='enrollment.TeacherDetails'),
        ),
    ]
