# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-19 16:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0004_offering_units'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offering',
            name='units',
        ),
    ]
