# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-26 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0005_remove_offering_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='units',
            field=models.IntegerField(null=True),
        ),
    ]
