# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-07 16:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0005_auto_20180107_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherdetails',
            old_name='employee_ID',
            new_name='employee_name',
        ),
    ]
