# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-28 21:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0006_subjects_units'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculum',
            name='school_year',
        ),
        migrations.RemoveField(
            model_name='curriculum',
            name='year_level',
        ),
        migrations.RemoveField(
            model_name='school_year',
            name='date_end',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='subject_description',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='subject_status',
        ),
        migrations.AddField(
            model_name='curriculum',
            name='curriculum_status',
            field=models.CharField(choices=[('a', 'Active'), ('i', 'Inactive')], default='a', max_length=1),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='curriculum_year',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
